spring.application.name=BulkEmail
#
email.file.location=files/email.html
mailboxes.file.location=files/mailboxes.txt
email.properties.file.location=files/email.properties
email.properties.smtp.file.location=files/smtp.properties
